repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: David Ramirez
title: Telecom Field Engineer
#email: Your email (optional)
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: 🚀 
website_title: <a href="https://dengineeringblog.github.io/ascend/">Technical Dives</a>


url: dengineeringblog.github.io
baseurl: /telecom_cv

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: jekyllrb
#github_username:  jekyll
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: telecom-engineer-5g-network
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/Profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  From the jungles of Suriname to sites all over the UK, I get the job done, properly and safely. 
  
  My commitment is simple: <mark>DELIVER RESULTS</mark>. 
  
  I’m ready for new challenges and to keep growing by putting my experience into action.



content:
  #- title: Projects # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: left
  #      border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
  #      title: Project name
  #      link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #      link_text: Link Text
  #      additional_links:
  #        - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          icon: fab fa-github
  #          url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #        - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          icon: fab fa-github
  #          url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #      quote: >
  #        Short overview of the project (optional)
  #      description: | # this will include new lines to allow paragraphs
  #        Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: left
        sub_title: Point-to-Point Communication (Microwave Links)
        # sub_title: Job title
        # caption: Date Range (eg. November 2016 - present)
        # link: Link to company (optional)
        # quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Hands-on experience in the <mark>installation</mark>, <mark>alignment</mark>, and <mark>troubleshooting</mark> of point-to-point microwave links. I’ve worked with a wide range of antenna sizes, including dishes up to 3.2 meters in diameter, often in remote environments and at heights above 100 meters.
          
          In Suriname, I was responsible for deploying and aligning microwave links in the jungle, often under challenging conditions.
          I’ve also collaborated in performing <a href="https://en.wikipedia.org/wiki/Y.1564">Y.1564 test</a>.

          Besides fieldwork, I’ve shared some of my experience through <a href="https://dengineeringblog.github.io/ascend/">technical articles</a> about microwave systems, a way to give back to the community and keep learning myself.

      - layout: left
        sub_title: Team Leader / Person in Charge
        # sub_title: Job title
        # caption: Date Range (eg. November 2016 - present)
        # link: Link to company (optional)
        # quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          I don’t believe leadership is about titles, it’s about taking <mark>responsibility</mark> and delivering <mark>results</mark>. I’ve led multi-country field teams, under pressure and in tough environments.

          When I’m in charge, the job gets done: **properly executed**. That’s is the standard. 

          My approach is simple: *lead by example*, *communicate clearly*, *keep safety first*, and *make sure the team knows they can count on me*.

      - layout: left
        sub_title: Senior Rigger & Telecom Installations
        # sub_title: Job title
        # caption: Date Range (eg. November 2016 - present)
        # link: Link to company (optional)
        # quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          I’ve spent years working at height, in Suriname, where sites are deep in the jungle with difficult access and hostile conditions, with towers up to 200 meters of height. and across the UK.

          As a Senior Rigger, I’ve carried out <mark>full telecom installations</mark>, <mark>upgrades</mark>, and <mark>equipment swaps</mark>. I’ve worked with equipment from <mark>Huawei</mark>, <mark>Nokia</mark>, <mark>Ericsson</mark>, and others, handling both the **rigging** and **technical side** of installations.
    

      - layout: left
        sub_title: Radio Frequency Testing
        # sub_title: Job title
        # caption: Date Range (eg. November 2016 - present)
        # link: Link to company (optional)
        # quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          I’ve worked as an RF Test Engineer, performing both **stationary** and **mobility** testing for <mark>GSM</mark>, <mark>UMTS</mark>, and <mark>LTE</mark> networks. During projects with Digicel and Telesur in Suriname (2020–2022), I helped **map signal coverage**, **benchmark performance**, and **optimize the network**.

          This role gave me a deep understanding of how mobile networks work, from user experience to cell site behavior. 

          Through this experience, I developed strong knowledge of key network parameters, and also understand the why behind the numbers.


      - layout: left
        sub_title: Troubleshooting
        # sub_title: Job title
        # caption: Date Range (eg. November 2016 - present)
        # link: Link to company (optional)
        # quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Over the years, I’ve solved <mark>Layer 1 issues</mark> such as:

          - Microwave link misalignment, including cases where the installation was poorly executed. My team has successfully completed installations that other teams couldn’t finish, and we’ve also troubleshooted issues caused by mistakes during their installation work.

          - Faulty feeders, jumpers, or connectors causing signal loss. I’ve diagnosed and documented these issues in my <a href="https://drive.google.com/file/d/1s7nTFxnWGjPIEsbrzFRyQPrRSji4fYp1/view?usp=sharing">technical reports</a>.
          In some cases, I’ve supported my company by providing evidence during VSWR investigations, showing that the root cause was in legacy infrastructure, not in the installation carried out by my company.


          These hands-on experiences have helped me quickly identify root causes and apply practical solutions on site.


      - layout: left
        sub_title: Surveys
        # sub_title: Job title
        # caption: Date Range (eg. November 2016 - present)
        # link: Link to company (optional)
        # quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Hands-on experience conducting both <mark>pre-build</mark> surveys for microwave deployments and <mark>infrastructure</mark> surveys to assess site structural conditions.

          My work includes:

          - Line-of-sight (LOS) surveys to validate clear paths for point-to-point microwave links.

          - Pre-build site assessments to plan equipment layout, cable routing, and mounting points.

          - Tower and rooftop infrastructure surveys to check structural integrity, grounding systems, and available space.

               

  - title: Certifications
    layout: list
    content:
      - layout: left
        sub_title: Rigging and Abseiling
        # sub_title: Job title
        # caption: Date Range (eg. November 2016 - present)
        # link: Link to company (optional)
        # quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          I hold the required UK certifications for *Rigging* and *Abseiling*. These include: <mark> Basic Tower Climber and Rescue  </mark>, <mark> Rigging and Lifting of Light Loads </mark>, <mark> Rooftop Safety and Access </mark>, 
          <mark> Basic Tower Climber and Rescue  </mark>, <mark> Radio Frequency Awareness </mark>, <mark> Emergency First Aid </mark> and <mark> Basic Abseil</mark>  with Arco Professional Safety Services.
      - layout: left
        sub_title: Technical Certs
        # sub_title: Job title
        # caption: Date Range (eg. November 2016 - present)
        # link: Link to company (optional)
        # quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          I’m not the person who collects certificates just to show them off, I believe in practical, hands-on skills that make a real difference in the field.

          That said, I’ve been doing the *"homework"*, expanding my technical knowledge. That includes multiple certifications from **Anritsu**: <mark> RF Fundamentals</mark>  - <mark> Radio Frequency: Module 1</mark>  - <mark> Decibels: Module 2</mark>  - <mark> Modulation: Module 3</mark>  - <mark> RF Impairment: Module 4</mark>  - <mark> Antennas: Module 5</mark>  - <mark> Coaxial Cables: Module 6</mark>  - <mark> Components: Module 7</mark>  - <mark> Propagation: Module 8</mark>  - <mark> Microwave: Module 9</mark>, <mark> Waveguide Line Sweeping </mark>,
          <mark> Site Master Line Sweep Online Prep for In-Person Training </mark>,  <mark> Portable PIM Master </mark>, <mark> Passive DAS Installation & Testing </mark>.

  
  - title: Education
    layout: list
    content:
      - layout: left
        title: Automation Engineer
        sub_title: UK Framework - RQF Level 6 / SCQF Level 10 / CQFW Level 6
        caption: 2019
        # quote: >
        #  Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Automation Engineering is often misunderstood as related to automotive technology; however, it is a discipline focused on industrial automation, control systems, 
          and process optimization across a wide range of industries, including manufacturing, energy, and infrastructure.

          Throughout my 5 years career path, I developed a strong foundation in  technical areas that are highly transferable to other engineering domains.
          Key areas of study included: <mark> Electronics </mark>, <mark>Industrial Instrumentation & Measurement </mark>, <mark> SCADA Systems </mark>(Supervisory Control and Data Acquisition), <mark> PLC Programming </mark>, <mark> Programming </mark>(in general).

          Feel free to request my Statement of Comparability with the <a href="https://assets.publishing.service.gov.uk/media/5dada244ed915d42a05eea26/Referencing_the_Qualifications_Frameworks_of_England_and_Northern_Ireland_to_the_European_Qualifications_Framework.pdf">UK Framework</a> if needed. 
  #- title: A Little More About Me
  #  layout: text
  #  content: | # this will include new lines to allow paragraphs
  #    This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

  #    Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
